### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by fmohican** [electro2560/ForceGrow#1]
Hello @electro2560 ,
Can you update the plugin to work with 1.14.x ?

Thanks you!

**Comment by electro2560** [comment]
Have you tested it in 1.14? It may already be compatible.

**Comment by fmohican** [comment]
Yes i tried on 1.14 [Paper - 186]

Also if its possible to add option, to disable "ForceGrow" on some world. like

```
Blacklistedworld:
- X
- Y
- Z
```

and to grow saplings in same way

**Comment by electro2560** [comment]
Were any errors reported in console?

I'll add a blacklisted worlds list too. Would that also prevent saplings from growing in that world?

**Comment by fmohican** [comment]
yah, would be nice ;P

**Comment by electro2560** [comment]
Support for 1.13+ has been added in v1.0.4. https://www.spigotmc.org/resources/%E2%AD%90-force-grow-%E2%AD%90.37871/updates

**Comment by electro2560** [comment]
Add this to your config to disable certain worlds. Preventing saplings from growing will need to be handled by a different plugin because that's not the focus of this plugin. To do that you should use something like Multiverse or WorldGuard.

```
#Worlds ForceGrow is disabled in. These are case sensitive.
disabled-worlds:
  - example1
  - example2
```

**Comment by fmohican** [comment]
thanks!
